spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trade
    username: ${TRADE_POSTGRES_USERNAME}
    password: ${TRADE_POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
    sql-script-encoding: UTF-8

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: GMT+4
    hibernate:
      ddl-auto: update
logging:
  file:
    name: logs/app.log

server:
  port: 8084
  error:
    whitelabel:
      enabled: false


---
#spring:
#  profiles: test
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration